Finish top navigation bar
meghakak/step pull request #4
Opened 2020-06-23 18:33 UTC by meghakak

2020-06-23 20:44 UTC, linhnguye-g requested changes
Sorry for all the nits, want to make sure style is consistent and clean.

It seems you are copying the same code for the nav bar into multiple files. Generally it's best to avoid having the exact same lines in multiple places. Imagine in a larger codebase, if you want to make a change to the nav bar, you now have to edit all the pages instead of a single place. This can get pretty complicated, especially if a file is missed.

I'm not entirely sure the best way to simplify this in HTML, it would be good to ask the Virtual Support Engineers about how you could reuse the nav bar on multiple pages.

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/blog.html
> +        <a href="blog.html">STEP Blog</a>
nit: Indent by 2 spaces at a time. Don’t use tabs or mix tabs and spaces for indentation.
https://google.github.io/styleguide/htmlcssguide.html#Indentation

I think these are indented by 4 spaces, please change to 2 to be consistent with rest of the file

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/gallery.html
> +        <a href="blog.html">STEP Blog</a>
nit: Indent by 2 spaces at a time. Don’t use tabs or mix tabs and spaces for indentation.
https://google.github.io/styleguide/htmlcssguide.html#Indentation

I think these are indented by 4 spaces, please change to 2 to be consistent with rest of the file

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/hobbies.html
> +        <a href="blog.html">STEP Blog</a>
nit: Indent by 2 spaces at a time. Don’t use tabs or mix tabs and spaces for indentation.
https://google.github.io/styleguide/htmlcssguide.html#Indentation

I think these are indented by 4 spaces, please change to 2 to be consistent with rest of the file

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/index.html
> +        <a href="blog.html">STEP Blog</a>
nit: Indent by 2 spaces at a time. Don’t use tabs or mix tabs and spaces for indentation.
https://google.github.io/styleguide/htmlcssguide.html#Indentation

I think these are indented by 4 spaces, please change to 2 to be consistent with rest of the file

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/style.css
> +.title {
nit: Please change back to the two space indent style for the file

https://google.github.io/styleguide/htmlcssguide.html#Indentation

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/blog.html
> +  <body bgcolor="#ff9999">
Can this be moved to style.css? 

From checking validity, it seems like the bgcolor attribute is obsolete?
https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity

Same happens to the `<hr color=black>` tag as well.

And if so could you change this for the other files as well? Thanks!

2020-06-23 20:44 UTC, linhnguye-g commented on portfolio/src/main/webapp/index.html
>          and to put together music playlists for my friends!
Sorry I missed this last time but could you add an alt attribute to the image below as well. And remove the `/` from the img end tag as it is not needed

https://google.github.io/styleguide/htmlcssguide.html#Multimedia_Fallback

2020-06-23 20:53 UTC, christophervo-g reviewed
Looks mostly good! One minor nit in addition to all the style nits Linh pointed out :)

2020-06-23 20:53 UTC, christophervo-g commented on portfolio/src/main/webapp/hobbies.html
> +
nit: unnecessary blank line

2020-06-23 23:40 UTC, linhnguye-g commented on portfolio/src/main/webapp/blog.html
> +  <body bgcolor="#ff9999">
Also for completeness, just saw this: https://google.github.io/styleguide/htmlcssguide.html#Separation_of_Concerns

2020-06-24 01:12 UTC, meghakak commented on portfolio/src/main/webapp/blog.html
> +        <a href="blog.html">STEP Blog</a>
Sorry about all the wrong indentations and thank you for catching them!

2020-06-24 04:20 UTC, linhnguye-g approved these changes
LGTM! Please do remove the space if it isn't necessary before submitting. Great job Megha!

2020-06-24 04:20 UTC, linhnguye-g commented on portfolio/src/main/webapp/blog.html
> +    <div id="top-navigation"> </div>
nit: Are the spaces between the opening and closing div needed here? If not please remove! Please do the same for the other files as well!

2020-06-24 15:47 UTC, christophervo-g approved these changes
LGTM!

2020-06-24 15:49 UTC, merged